chore: add default templates to create new issues and raise pull requests
polarsource/polar pull request #4110
Opened 2024-10-08 18:35 UTC by apsinghdev

fixes: #4102

This PR adds default templates to create new issues and raise pull requests.

<img width="1258" alt="Screenshot 2024-10-09 at 12 04 57 AM" src="https://github.com/user-attachments/assets/bf29333e-8488-4460-9292-52e928f96f3f">

2024-10-09 06:57 UTC, frankie567 requested changes
Thank you for this, @apsinghdev! That's really helpful and will clearly help newcomers being guided to the right channel.

Just a few tweaks and we should be good to go 👍

2024-10-09 06:57 UTC, frankie567 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +### Checklist
I would remove that checklist, not so useful in my experience 😄

2024-10-09 06:57 UTC, frankie567 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +---
Love that last part (lines 38-42) 😄 However, I would put it in HTML comments, it doesn't have to appear in the body of the issue.

2024-10-09 06:57 UTC, frankie567 commented on .github/ISSUE_TEMPLATE/config.yml
> +  - name: 🛟 Improvement Request
This is a bit redundant with Feature Request. I would prefer to have a support link to our Discord. Something like:

```yml
  - name: 🛟 Support
    url: https://discord.com/invite/STfRufb32V
    about: Join us on Discord to ask support questions
```

2024-10-09 06:57 UTC, frankie567 commented on .github/PULL_REQUEST_TEMPLATE.md
> +## Description
I appreciate your effort of setting up a PR template; however, I would remove it.

Currently, most of our PR are either done by Polar team or by contributors we already gave guidance to on Discord and/or GitHub issues. So, I don't think we need it right now :)

2024-10-09 06:57 UTC, frankie567 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: "Issue-Bug"
Our label is `bug`

2024-10-09 15:39 UTC, apsinghdev commented
@frankie567 Thanks a lot for the feedback! I have updated the PR with the necessary changes. Please have a look.

2024-10-09 15:41 UTC, frankie567 commented
Amazing! Thank you for this @apsinghdev 🙏

2024-10-09 15:41 UTC, merged

2024-10-10 16:01 UTC, apsinghdev commented
> Amazing! Thank you for this @apsinghdev 🙏

Thanks!